version: "3.9"

services:
  db:
    image: postgres
    container_name: database_study
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=study
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: backend_study
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:
    driver: local
